In [1]:
# ============================================================
# BÀI 1 - HIỂU DỮ LIỆU, CHỌN DỮ LIỆU VÀ TIỀN XỬ LÝ
# DATASET 1: RETAIL SALES & CUSTOMER BEHAVIOR
# ============================================================

# 1. Import thư viện
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)
print("Đã tải thư viện thành công!")


# 2. Đọc Dataset 1
retail_path = "../data/raw/archive/retail_data.csv"

retail = pd.read_csv(retail_path)


# 3. Kiểm tra quy mô dữ liệu
print("\n=== QUY MÔ DATASET 1 ===")
print("Kích thước dataset:", retail.shape)
print("Số bản ghi:", retail.shape[0])
print("Số thuộc tính:", retail.shape[1])


# 4. Hiển thị 5 bản ghi đầu tiên
print("\n=== 5 BẢN GHI ĐẦU TIÊN ===")
display(retail.head())


# 5. Kiểm tra cấu trúc dữ liệu
print("\n=== THÔNG TIN DATASET 1 ===")
retail.info()


# 6. Danh sách các thuộc tính
print("\n=== DANH SÁCH THUỘC TÍNH ===")
for i, col in enumerate(retail.columns, 1):
    print(f"{i}. {col}")

# ============================================================
# 7. KHẢO SÁT CHẤT LƯỢNG DỮ LIỆU - DATASET 1
# ============================================================

# --- Giá trị thiếu ---
missing_count = retail.isnull().sum()
missing_percent = (missing_count / len(retail) * 100).round(2)

missing_table = pd.DataFrame({
    "Số giá trị thiếu": missing_count,
    "Tỷ lệ thiếu (%)": missing_percent
})

missing_table = missing_table[missing_table["Số giá trị thiếu"] > 0]
missing_table = missing_table.sort_values(
    "Tỷ lệ thiếu (%)",
    ascending=False
)

print("=== GIÁ TRỊ THIẾU ===")

if len(missing_table) == 0:
    print("Không phát hiện giá trị thiếu.")
else:
    display(missing_table)


# --- Dữ liệu trùng lặp ---
duplicate_count = retail.duplicated().sum()

print("\n=== DỮ LIỆU TRÙNG LẶP ===")
print("Số dòng trùng lặp:", duplicate_count)
print(
    "Tỷ lệ trùng lặp:",
    round(duplicate_count / len(retail) * 100, 2),
    "%"
)


# --- Phân loại kiểu thuộc tính ---
numeric_cols = retail.select_dtypes(include=np.number).columns.tolist()
categorical_cols = retail.select_dtypes(exclude=np.number).columns.tolist()

print("\n=== KIỂU THUỘC TÍNH ===")
print("Số thuộc tính dạng số:", len(numeric_cols))
print("Số thuộc tính dạng phân loại/text:", len(categorical_cols))

print("\nThuộc tính dạng số:")
print(numeric_cols)

print("\nThuộc tính dạng phân loại/text:")
print(categorical_cols)


# --- Thống kê mô tả ---
print("\n=== THỐNG KÊ MÔ TẢ CÁC THUỘC TÍNH SỐ ===")
display(retail[numeric_cols].describe().T)

Pandas: 3.0.6
NumPy: 2.5.3
Đã tải thư viện thành công!

=== QUY MÔ DATASET 1 ===
Kích thước dataset: (1000000, 78)
Số bản ghi: 1000000
Số thuộc tính: 78

=== 5 BẢN GHI ĐẦU TIÊN ===

,customer_id,age,gender,income_bracket,loyalty_program,membership_years,churned,marital_status,number_of_children,education_level,...,distance_to_store,holiday_season,season,weekend,customer_support_calls,email_subscriptions,app_usage,website_visits,social_media_engagement,days_since_last_purchase
0,1,56,Other,High,No,0,No,Divorced,3,Bachelor's,...,33.21,No,Spring,Yes,5,No,High,30,High,40
1,2,69,Female,Medium,No,2,No,Married,2,PhD,...,62.56,No,Summer,Yes,6,No,High,40,Medium,338
2,3,46,Female,Low,No,5,No,Married,3,Bachelor's,...,83.04,Yes,Winter,Yes,2,Yes,Low,89,Medium,61
3,4,32,Female,Low,No,0,No,Divorced,2,Master's,...,50.43,Yes,Winter,No,12,No,Low,12,Low,42
4,5,60,Female,Low,Yes,7,Yes,Divorced,2,Bachelor's,...,36.55,Yes,Summer,Yes,3,No,Medium,31,Low,242

=== THÔNG TIN DATASET 1 ===
<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 78 columns):
 #   Column                     Non-Null Count    Dtype
---  ------                     --------------    -----
 0   customer_id                1000000 non-null  int64
 1   age                        1000000 non-null  int64
 2   gender                     1000000 non-null  str
 3   income_bracket             1000000 non-null  str
 4   loyalty_program            1000000 non-null  str
 5   membership_years           1000000 non-null  int64
 6   churned                    1000000 non-null  str
 7   marital_status             1000000 non-null  str
 8   number_of_children         1000000 non-null  int64
 9   education_level            1000000 non-null  str
 10  occupation                 1000000 non-null  str
 11  transaction_id             1000000 non-null  int64
 12  transaction_date           1000000 non-null  str
 13  product_id                 1000000 non-null  int64
 14  product_category           1000000 non-null  str
 15  quantity                   1000000 non-null  int64
 16  unit_price                 1000000 non-null  float64
 17  discount_applied           1000000 non-null  float64
 18  payment_method             1000000 non-null  str
 19  store_location             1000000 non-null  str
 20  transaction_hour           1000000 non-null  int64
 21  day_of_week                1000000 non-null  str
 22  week_of_year               1000000 non-null  int64
 23  month_of_year              1000000 non-null  int64
 24  avg_purchase_value         1000000 non-null  float64
 25  purchase_frequency         1000000 non-null  str
 26  last_purchase_date         1000000 non-null  str
 27  avg_discount_used          1000000 non-null  float64
 28  preferred_store            1000000 non-null  str
 29  online_purchases           1000000 non-null  int64
 30  in_store_purchases         1000000 non-null  int64
 31  avg_items_per_transaction  1000000 non-null  float64
 32  avg_transaction_value      1000000 non-null  float64
 33  total_returned_items       1000000 non-null  int64
 34  total_returned_value       1000000 non-null  float64
 35  total_sales                1000000 non-null  float64
 36  total_transactions         1000000 non-null  int64
 37  total_items_purchased      1000000 non-null  int64
 38  total_discounts_received   1000000 non-null  float64
 39  avg_spent_per_category     1000000 non-null  float64
 40  max_single_purchase_value  1000000 non-null  float64
 41  min_single_purchase_value  1000000 non-null  float64
 42  product_name               1000000 non-null  str
 43  product_brand              1000000 non-null  str
 44  product_rating             1000000 non-null  float64
 45  product_review_count       1000000 non-null  int64
 46  product_stock              1000000 non-null  int64
 47  product_return_rate        1000000 non-null  float64
 48  product_size               1000000 non-null  str
 49  product_weight             1000000 non-null  float64
 50  product_color              1000000 non-null  str
 51  product_material           1000000 non-null  str
 52  product_manufacture_date   1000000 non-null  str
 53  product_expiry_date        1000000 non-null  str
 54  product_shelf_life         1000000 non-null  int64
 55  promotion_id               1000000 non-null  int64
 56  promotion_type             1000000 non-null  str
 57  promotion_start_date       1000000 non-null  str
 58  promotion_end_date         1000000 non-null  str
 59  promotion_effectiveness    1000000 non-null  str
 60  promotion_channel          1000000 non-null  str
 61  promotion_target_audience  1000000 non-null  str
 62  customer_zip_code          1000000 non-null  int64
 63  customer_city              1000000 non-null  str
 64  customer_state             1000000 non-null  str
 65  store_zip_code             1000000 non-null  int64
 66  store_city                 1000000 non-null  str
 67  store_state                1000000 non-null  str
 68  distance_to_store          1000000 non-null  float64
 69  holiday_season             1000000 non-null  str
 70  season                     1000000 non-null  str
 71  weekend                    1000000 non-null  str
 72  customer_support_calls     1000000 non-null  int64
 73  email_subscriptions        1000000 non-null  str
 74  app_usage                  1000000 non-null  str
 75  website_visits             1000000 non-null  int64
 76  social_media_engagement    1000000 non-null  str
 77  days_since_last_purchase   1000000 non-null  int64
dtypes: float64(16), int64(24), str(38)
memory usage: 595.1 MB

=== DANH SÁCH THUỘC TÍNH ===
1. customer_id
2. age
3. gender
4. income_bracket
5. loyalty_program
6. membership_years
7. churned
8. marital_status
9. number_of_children
10. education_level
11. occupation
12. transaction_id
13. transaction_date
14. product_id
15. product_category
16. quantity
17. unit_price
18. discount_applied
19. payment_method
20. store_location
21. transaction_hour
22. day_of_week
23. week_of_year
24. month_of_year
25. avg_purchase_value
26. purchase_frequency
27. last_purchase_date
28. avg_discount_used
29. preferred_store
30. online_purchases
31. in_store_purchases
32. avg_items_per_transaction
33. avg_transaction_value
34. total_returned_items
35. total_returned_value
36. total_sales
37. total_transactions
38. total_items_purchased
39. total_discounts_received
40. avg_spent_per_category
41. max_single_purchase_value
42. min_single_purchase_value
43. product_name
44. product_brand
45. product_rating
46. product_review_count
47. product_stock
48. product_return_rate
49. product_size
50. product_weight
51. product_color
52. product_material
53. product_manufacture_date
54. product_expiry_date
55. product_shelf_life
56. promotion_id
57. promotion_type
58. promotion_start_date
59. promotion_end_date
60. promotion_effectiveness
61. promotion_channel
62. promotion_target_audience
63. customer_zip_code
64. customer_city
65. customer_state
66. store_zip_code
67. store_city
68. store_state
69. distance_to_store
70. holiday_season
71. season
72. weekend
73. customer_support_calls
74. email_subscriptions
75. app_usage
76. website_visits
77. social_media_engagement
78. days_since_last_purchase
=== GIÁ TRỊ THIẾU ===
Không phát hiện giá trị thiếu.

=== DỮ LIỆU TRÙNG LẶP ===
Số dòng trùng lặp: 0
Tỷ lệ trùng lặp: 0.0 %

=== KIỂU THUỘC TÍNH ===
Số thuộc tính dạng số: 40
Số thuộc tính dạng phân loại/text: 38

Thuộc tính dạng số:
['customer_id', 'age', 'membership_years', 'number_of_children', 'transaction_id', 'product_id', 'quantity', 'unit_price', 'discount_applied', 'transaction_hour', 'week_of_year', 'month_of_year', 'avg_purchase_value', 'avg_discount_used', 'online_purchases', 'in_store_purchases', 'avg_items_per_transaction', 'avg_transaction_value', 'total_returned_items', 'total_returned_value', 'total_sales', 'total_transactions', 'total_items_purchased', 'total_discounts_received', 'avg_spent_per_category', 'max_single_purchase_value', 'min_single_purchase_value', 'product_rating', 'product_review_count', 'product_stock', 'product_return_rate', 'product_weight', 'product_shelf_life', 'promotion_id', 'customer_zip_code', 'store_zip_code', 'distance_to_store', 'customer_support_calls', 'website_visits', 'days_since_last_purchase']

Thuộc tính dạng phân loại/text:
['gender', 'income_bracket', 'loyalty_program', 'churned', 'marital_status', 'education_level', 'occupation', 'transaction_date', 'product_category', 'payment_method', 'store_location', 'day_of_week', 'purchase_frequency', 'last_purchase_date', 'preferred_store', 'product_name', 'product_brand', 'product_size', 'product_color', 'product_material', 'product_manufacture_date', 'product_expiry_date', 'promotion_type', 'promotion_start_date', 'promotion_end_date', 'promotion_effectiveness', 'promotion_channel', 'promotion_target_audience', 'customer_city', 'customer_state', 'store_city', 'store_state', 'holiday_season', 'season', 'weekend', 'email_subscriptions', 'app_usage', 'social_media_engagement']

=== THỐNG KÊ MÔ TẢ CÁC THUỘC TÍNH SỐ ===

,count,mean,std,min,25%,50%,75%,max
customer_id,1000000.0,500000.500000,288675.278932,1.00,250000.7500,500000.500,750000.2500,1000000.00
age,1000000.0,48.496605,17.874381,18.00,33.0000,49.000,64.0000,79.00
membership_years,1000000.0,4.497453,2.872406,0.00,2.0000,4.000,7.0000,9.00
number_of_children,1000000.0,2.000554,1.414214,0.00,1.0000,2.000,3.0000,4.00
transaction_id,1000000.0,499891.731447,288706.057652,2.00,249878.7500,499559.500,750071.2500,999999.00
product_id,1000000.0,4999.564515,2886.798391,1.00,2498.0000,4999.000,7498.0000,9999.00
quantity,1000000.0,5.002649,2.583751,1.00,3.0000,5.000,7.0000,9.00
unit_price,1000000.0,500.261317,288.462860,1.00,250.3100,500.410,750.1600,1000.00
discount_applied,1000000.0,0.249910,0.144328,0.00,0.1300,0.250,0.3700,0.50
transaction_hour,1000000.0,11.505193,6.924460,0.00,5.0000,12.000,18.0000,23.00
week_of_year,1000000.0,26.503691,15.005165,1.00,14.0000,27.000,39.0000,52.00
month_of_year,1000000.0,6.497467,3.455212,1.00,3.0000,7.000,10.0000,12.00
avg_purchase_value,1000000.0,254.886444,141.494923,10.00,132.2200,254.930,377.3500,500.00
avg_discount_used,1000000.0,0.250010,0.144383,0.00,0.1300,0.250,0.3800,0.50
online_purchases,1000000.0,49.446018,28.861439,0.00,24.0000,49.000,74.0000,99.00
in_store_purchases,1000000.0,49.484486,28.882712,0.00,24.0000,49.000,75.0000,99.00
avg_items_per_transaction,1000000.0,5.503122,2.597661,1.00,3.2600,5.500,7.7500,10.00
avg_transaction_value,1000000.0,255.115768,141.430014,10.00,132.5100,255.230,377.6700,500.00
total_returned_items,1000000.0,4.498142,2.872805,0.00,2.0000,4.000,7.0000,9.00
total_returned_value,1000000.0,500.387837,288.717476,0.00,250.6300,500.400,750.3900,1000.00
total_sales,1000000.0,5056.059765,2859.100058,100.01,2577.8675,5059.695,7534.8025,9999.98
total_transactions,1000000.0,49.987386,28.571689,1.00,25.0000,50.000,75.0000,99.00
total_items_purchased,1000000.0,250.042763,143.984546,1.00,125.0000,250.000,375.0000,499.00
total_discounts_received,1000000.0,499.674388,288.579102,0.00,249.7600,499.510,749.5400,1000.00
avg_spent_per_category,1000000.0,505.175478,286.059178,10.00,257.2400,505.140,753.0600,1000.00
max_single_purchase_value,1000000.0,505.001404,286.073324,10.00,256.8400,505.220,753.2100,1000.00
min_single_purchase_value,1000000.0,5.043849,2.855905,0.10,2.5700,5.040,7.5100,10.00
product_rating,1000000.0,2.999010,1.154801,1.00,2.0000,3.000,4.0000,5.00
product_review_count,1000000.0,499.235198,288.446150,0.00,250.0000,499.000,749.0000,999.00
product_stock,1000000.0,49.515129,28.876645,0.00,25.0000,49.000,75.0000,99.00
product_return_rate,1000000.0,0.250137,0.144408,0.00,0.1300,0.250,0.3800,0.50
product_weight,1000000.0,5.054372,2.857848,0.10,2.5800,5.060,7.5300,10.00
product_shelf_life,1000000.0,181.876207,105.228855,0.00,91.0000,182.000,273.0000,364.00
promotion_id,1000000.0,499.920037,288.453056,1.00,250.0000,500.000,750.0000,999.00
customer_zip_code,1000000.0,54993.644773,25975.807799,10000.00,32477.7500,54966.000,77493.0000,99998.00
store_zip_code,1000000.0,54972.766714,25981.483139,10000.00,32473.0000,54961.000,77451.0000,99998.00
distance_to_store,1000000.0,49.979109,28.860989,0.00,24.9700,49.960,74.9500,100.00
customer_support_calls,1000000.0,9.496269,5.761233,0.00,4.0000,9.000,14.0000,19.00
website_visits,1000000.0,49.512951,28.869777,0.00,25.0000,50.000,75.0000,99.00
days_since_last_purchase,1000000.0,182.027559,105.364598,0.00,91.0000,182.000,273.0000,364.00

In [2]:
# KIỂM TRA GIÁ TRỊ THIẾU VÀ TRÙNG LẶP

print("=== GIÁ TRỊ THIẾU ===")

missing = retail.isnull().sum()
missing = missing[missing > 0]

if len(missing) == 0:
    print("Không phát hiện giá trị thiếu.")
else:
    print(missing)

print("\n=== DỮ LIỆU TRÙNG LẶP ===")

duplicate_count = retail.duplicated().sum()

print("Số dòng trùng lặp:", duplicate_count)
print(
    "Tỷ lệ trùng lặp:",
    round(duplicate_count / len(retail) * 100, 2),
    "%"
)

=== GIÁ TRỊ THIẾU ===
Không phát hiện giá trị thiếu.

=== DỮ LIỆU TRÙNG LẶP ===
Số dòng trùng lặp: 0
Tỷ lệ trùng lặp: 0.0 %

In [3]:
# ============================================================
# KIỂM TRA NGOẠI LAI (OUTLIER) - DATASET 1
# Phương pháp IQR
# ============================================================

# Lấy các thuộc tính dạng số
numeric_cols = retail.select_dtypes(include=np.number).columns

outlier_results = []

for col in numeric_cols:
    Q1 = retail[col].quantile(0.25)
    Q3 = retail[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outlier_count = (
        (retail[col] < lower_bound) |
        (retail[col] > upper_bound)
    ).sum()

    outlier_percent = round(
        outlier_count / len(retail) * 100, 2
    )

    outlier_results.append([
        col,
        outlier_count,
        outlier_percent
    ])

outlier_table = pd.DataFrame(
    outlier_results,
    columns=[
        "Thuộc tính",
        "Số ngoại lai",
        "Tỷ lệ (%)"
    ]
)

# Chỉ hiển thị những thuộc tính có ngoại lai
outlier_table = outlier_table[
    outlier_table["Số ngoại lai"] > 0
].sort_values("Tỷ lệ (%)", ascending=False)

print("=== NGOẠI LAI THEO PHƯƠNG PHÁP IQR ===")

if len(outlier_table) == 0:
    print("Không phát hiện ngoại lai bằng phương pháp IQR.")
else:
    display(outlier_table)

=== NGOẠI LAI THEO PHƯƠNG PHÁP IQR ===
Không phát hiện ngoại lai bằng phương pháp IQR.

In [4]:
# ============================================================
# DATASET 2: DIABETES 130-US HOSPITALS
# ============================================================

# Đường dẫn đến dữ liệu
diabetes_path = "../data/raw/diabetes+130-us+hospitals+for+years+1999-2008/diabetic_data.csv"

# Đọc dữ liệu
diabetes = pd.read_csv(diabetes_path)

# Kiểm tra quy mô
print("=== QUY MÔ DATASET 2 ===")
print("Kích thước dataset:", diabetes.shape)
print("Số bản ghi:", diabetes.shape[0])
print("Số thuộc tính:", diabetes.shape[1])

# Hiển thị 5 bản ghi đầu tiên
print("\n=== 5 BẢN GHI ĐẦU TIÊN ===")
display(diabetes.head())

# Thông tin cấu trúc
print("\n=== THÔNG TIN DATASET 2 ===")
diabetes.info()

=== QUY MÔ DATASET 2 ===
Kích thước dataset: (101766, 50)
Số bản ghi: 101766
Số thuộc tính: 50

=== 5 BẢN GHI ĐẦU TIÊN ===

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),?,6,25,1,1,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),?,1,1,7,3,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),?,1,1,7,2,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),?,1,1,7,2,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),?,1,1,7,1,...,No,Steady,No,No,No,No,No,Ch,Yes,NO

=== THÔNG TIN DATASET 2 ===
<class 'pandas.DataFrame'>
RangeIndex: 101766 entries, 0 to 101765
Data columns (total 50 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   encounter_id              101766 non-null  int64
 1   patient_nbr               101766 non-null  int64
 2   race                      101766 non-null  str
 3   gender                    101766 non-null  str
 4   age                       101766 non-null  str
 5   weight                    101766 non-null  str
 6   admission_type_id         101766 non-null  int64
 7   discharge_disposition_id  101766 non-null  int64
 8   admission_source_id       101766 non-null  int64
 9   time_in_hospital          101766 non-null  int64
 10  payer_code                101766 non-null  str
 11  medical_specialty         101766 non-null  str
 12  num_lab_procedures        101766 non-null  int64
 13  num_procedures            101766 non-null  int64
 14  num_medications           101766 non-null  int64
 15  number_outpatient         101766 non-null  int64
 16  number_emergency          101766 non-null  int64
 17  number_inpatient          101766 non-null  int64
 18  diag_1                    101766 non-null  str
 19  diag_2                    101766 non-null  str
 20  diag_3                    101766 non-null  str
 21  number_diagnoses          101766 non-null  int64
 22  max_glu_serum             5346 non-null    str
 23  A1Cresult                 17018 non-null   str
 24  metformin                 101766 non-null  str
 25  repaglinide               101766 non-null  str
 26  nateglinide               101766 non-null  str
 27  chlorpropamide            101766 non-null  str
 28  glimepiride               101766 non-null  str
 29  acetohexamide             101766 non-null  str
 30  glipizide                 101766 non-null  str
 31  glyburide                 101766 non-null  str
 32  tolbutamide               101766 non-null  str
 33  pioglitazone              101766 non-null  str
 34  rosiglitazone             101766 non-null  str
 35  acarbose                  101766 non-null  str
 36  miglitol                  101766 non-null  str
 37  troglitazone              101766 non-null  str
 38  tolazamide                101766 non-null  str
 39  examide                   101766 non-null  str
 40  citoglipton               101766 non-null  str
 41  insulin                   101766 non-null  str
 42  glyburide-metformin       101766 non-null  str
 43  glipizide-metformin       101766 non-null  str
 44  glimepiride-pioglitazone  101766 non-null  str
 45  metformin-rosiglitazone   101766 non-null  str
 46  metformin-pioglitazone    101766 non-null  str
 47  change                    101766 non-null  str
 48  diabetesMed               101766 non-null  str
 49  readmitted                101766 non-null  str
dtypes: int64(13), str(37)
memory usage: 38.8 MB

In [5]:
# ============================================================
# KIỂM TRA CHẤT LƯỢNG DỮ LIỆU - DATASET 2: DIABETES
# ============================================================

# 1. Kiểm tra giá trị thiếu dạng NaN
print("=== GIÁ TRỊ THIẾU DẠNG NaN ===")

missing_nan = diabetes.isnull().sum()
missing_nan = missing_nan[missing_nan > 0]

if len(missing_nan) == 0:
    print("Không phát hiện giá trị NaN.")
else:
    print(missing_nan)


# 2. Kiểm tra giá trị thiếu được ký hiệu bằng "?"
print("\n=== GIÁ TRỊ '?' ===")

question_mark_count = (diabetes == "?").sum()
question_mark_count = question_mark_count[question_mark_count > 0]

if len(question_mark_count) == 0:
    print("Không phát hiện giá trị '?'.")
else:
    question_mark_percent = (
        question_mark_count / len(diabetes) * 100
    ).round(2)

    question_mark_table = pd.DataFrame({
        "Số lượng '?'": question_mark_count,
        "Tỷ lệ (%)": question_mark_percent
    })

    display(question_mark_table)


# 3. Kiểm tra dòng trùng lặp
print("\n=== DỮ LIỆU TRÙNG LẶP ===")

duplicate_count = diabetes.duplicated().sum()

print("Số dòng trùng lặp:", duplicate_count)
print(
    "Tỷ lệ trùng lặp:",
    round(duplicate_count / len(diabetes) * 100, 2),
    "%"
)


# 4. Phân loại thuộc tính
numeric_cols_diabetes = diabetes.select_dtypes(
    include=np.number
).columns.tolist()

categorical_cols_diabetes = diabetes.select_dtypes(
    exclude=np.number
).columns.tolist()

print("\n=== KIỂU THUỘC TÍNH ===")
print("Số thuộc tính dạng số:", len(numeric_cols_diabetes))
print(
    "Số thuộc tính dạng phân loại/text:",
    len(categorical_cols_diabetes)
)

=== GIÁ TRỊ THIẾU DẠNG NaN ===
max_glu_serum    96420
A1Cresult        84748
dtype: int64

=== GIÁ TRỊ '?' ===

                   Số lượng '?'  Tỷ lệ (%)
race                       2273       2.23
weight                    98569      96.86
payer_code                40256      39.56
medical_specialty         49949      49.08
diag_1                       21       0.02
diag_2                      358       0.35
diag_3                     1423       1.40

=== DỮ LIỆU TRÙNG LẶP ===
Số dòng trùng lặp: 0
Tỷ lệ trùng lặp: 0.0 %

=== KIỂU THUỘC TÍNH ===
Số thuộc tính dạng số: 13
Số thuộc tính dạng phân loại/text: 37

In [6]:
# ============================================================
# DATASET 3: HUMAN ACTIVITY RECOGNITION USING SMARTPHONES
# ============================================================

# Thư mục gốc của Dataset 3
har_path = "../data/raw/human+activity+recognition+using+smartphones/UCI HAR Dataset/UCI HAR Dataset"

# 1. Đọc tên 561 thuộc tính
features = pd.read_csv(
    f"{har_path}/features.txt",
    sep=r"\s+",
    header=None,
    names=["feature_id", "feature_name"]
)

print("Số thuộc tính trong features.txt:", len(features))

# 2. Đọc dữ liệu Train
X_train = pd.read_csv(
    f"{har_path}/train/X_train.txt",
    sep=r"\s+",
    header=None
)

y_train = pd.read_csv(
    f"{har_path}/train/y_train.txt",
    sep=r"\s+",
    header=None,
    names=["activity"]
)

# 3. Đọc dữ liệu Test
X_test = pd.read_csv(
    f"{har_path}/test/X_test.txt",
    sep=r"\s+",
    header=None
)

y_test = pd.read_csv(
    f"{har_path}/test/y_test.txt",
    sep=r"\s+",
    header=None,
    names=["activity"]
)

# 4. Gộp train và test để khảo sát toàn bộ dataset
har = pd.concat([X_train, X_test], ignore_index=True)
har_target = pd.concat([y_train, y_test], ignore_index=True)

print("\n=== QUY MÔ DATASET 3 ===")
print("Train:", X_train.shape)
print("Test:", X_test.shape)
print("Toàn bộ dữ liệu:", har.shape)
print("Số bản ghi:", har.shape[0])
print("Số thuộc tính:", har.shape[1])

print("\n=== 5 BẢN GHI ĐẦU TIÊN ===")
display(har.head())

print("\n=== PHÂN BỐ NHÃN HOẠT ĐỘNG ===")
print(har_target["activity"].value_counts().sort_index())

Số thuộc tính trong features.txt: 561

=== QUY MÔ DATASET 3 ===
Train: (7352, 561)
Test: (2947, 561)
Toàn bộ dữ liệu: (10299, 561)
Số bản ghi: 10299
Số thuộc tính: 561

=== 5 BẢN GHI ĐẦU TIÊN ===

,0,1,2,3,4,5,6,7,8,9,...,551,552,553,554,555,556,557,558,559,560
0,0.288585,-0.020294,-0.132905,-0.995279,-0.983111,-0.913526,-0.995112,-0.983185,-0.923527,-0.934724,...,-0.074323,-0.298676,-0.710304,-0.112754,0.030400,-0.464761,-0.018446,-0.841247,0.179941,-0.058627
1,0.278419,-0.016411,-0.123520,-0.998245,-0.975300,-0.960322,-0.998807,-0.974914,-0.957686,-0.943068,...,0.158075,-0.595051,-0.861499,0.053477,-0.007435,-0.732626,0.703511,-0.844788,0.180289,-0.054317
2,0.279653,-0.019467,-0.113462,-0.995380,-0.967187,-0.978944,-0.996520,-0.963668,-0.977469,-0.938692,...,0.414503,-0.390748,-0.760104,-0.118559,0.177899,0.100699,0.808529,-0.848933,0.180637,-0.049118
3,0.279174,-0.026201,-0.123283,-0.996091,-0.983403,-0.990675,-0.997099,-0.982750,-0.989302,-0.938692,...,0.404573,-0.117290,-0.482845,-0.036788,-0.012892,0.640011,-0.485366,-0.848649,0.181935,-0.047663
4,0.276629,-0.016570,-0.115362,-0.998139,-0.980817,-0.990482,-0.998321,-0.979672,-0.990441,-0.942469,...,0.087753,-0.351471,-0.699205,0.123320,0.122542,0.693578,-0.615971,-0.847865,0.185151,-0.043892

=== PHÂN BỐ NHÃN HOẠT ĐỘNG ===
activity
1    1722
2    1544
3    1406
4    1777
5    1906
6    1944
Name: count, dtype: int64

In [7]:
# ============================================================
# KIỂM TRA CHẤT LƯỢNG DỮ LIỆU - DATASET 3: HAR
# ============================================================

# 1. Giá trị thiếu
print("=== GIÁ TRỊ THIẾU ===")

missing_har = har.isnull().sum()
missing_har = missing_har[missing_har > 0]

if len(missing_har) == 0:
    print("Không phát hiện giá trị thiếu.")
else:
    print(missing_har)


# 2. Dòng trùng lặp
print("\n=== DỮ LIỆU TRÙNG LẶP ===")

duplicate_har = har.duplicated().sum()

print("Số dòng trùng lặp:", duplicate_har)
print(
    "Tỷ lệ trùng lặp:",
    round(duplicate_har / len(har) * 100, 2),
    "%"
)


# 3. Kiểm tra kiểu dữ liệu
print("\n=== KIỂU DỮ LIỆU ===")

print(har.dtypes.value_counts())

print("Số thuộc tính dạng số:",
      len(har.select_dtypes(include=np.number).columns))

print("Số thuộc tính không phải dạng số:",
      len(har.select_dtypes(exclude=np.number).columns))


# 4. Kiểm tra giá trị vô hạn
print("\n=== GIÁ TRỊ VÔ HẠN ===")

inf_count = np.isinf(har.select_dtypes(include=np.number)).sum().sum()

print("Tổng số giá trị +inf/-inf:", inf_count)

=== GIÁ TRỊ THIẾU ===
Không phát hiện giá trị thiếu.

=== DỮ LIỆU TRÙNG LẶP ===
Số dòng trùng lặp: 0
Tỷ lệ trùng lặp: 0.0 %

=== KIỂU DỮ LIỆU ===
float64    561
Name: count, dtype: int64
Số thuộc tính dạng số: 561
Số thuộc tính không phải dạng số: 0

=== GIÁ TRỊ VÔ HẠN ===
Tổng số giá trị +inf/-inf: 0

## Đề xuất kỹ thuật khai phá dữ liệu

Sau khi khảo sát ba bộ dữ liệu, các kỹ thuật khai phá được đề xuất như sau:

| Dataset | Classification | Association | Clustering |
|---|---|---|---|
| Retail Sales & Customer Behavior | Có | Có | Có |
| Diabetes 130-US Hospitals | Có | Không | Có |
| Human Activity Recognition | Có | Không | Có |

### Dataset 1 - Retail Sales & Customer Behavior
- **Association:** Phân tích các sản phẩm hoặc nhóm sản phẩm thường xuất hiện cùng nhau trong giao dịch.
- **Classification:** Có thể sử dụng thuộc tính `churned` làm nhãn để xây dựng bài toán phân loại khách hàng.
- **Clustering:** Phân nhóm khách hàng dựa trên đặc điểm nhân khẩu học và hành vi mua sắm.

### Dataset 2 - Diabetes 130-US Hospitals
- **Classification:** Sử dụng thuộc tính `readmitted` làm nhãn để xây dựng bài toán phân loại tình trạng tái nhập viện.
- **Clustering:** Phân nhóm các lượt điều trị/bệnh nhân có đặc điểm tương đồng.

### Dataset 3 - Human Activity Recognition Using Smartphones
- **Classification:** Sử dụng `activity` làm nhãn để phân loại hoạt động của người dùng từ dữ liệu cảm biến.
- **Clustering:** Phân nhóm các mẫu dữ liệu cảm biến dựa trên mức độ tương đồng giữa các đặc trưng.

In [8]:
# ============================================================
# PHÂN TÍCH THUỘC TÍNH TRƯỚC TIỀN XỬ LÝ - DATASET 1
# ============================================================

attribute_info = pd.DataFrame({
    "Thuộc tính": retail.columns,
    "Kiểu dữ liệu": retail.dtypes.astype(str).values,
    "Số giá trị khác nhau": retail.nunique().values
})

display(attribute_info)

                  Thuộc tính Kiểu dữ liệu  Số giá trị khác nhau
0                customer_id        int64               1000000
1                        age        int64                    62
2                     gender          str                     3
3             income_bracket          str                     3
4            loyalty_program          str                     2
..                       ...          ...                   ...
73       email_subscriptions          str                     2
74                 app_usage          str                     3
75            website_visits        int64                   100
76   social_media_engagement          str                     3
77  days_since_last_purchase        int64                   365

[78 rows x 3 columns]

In [9]:
# ============================================================
# HIỂN THỊ ĐẦY ĐỦ 78 THUỘC TÍNH - DATASET 1
# ============================================================

for i, col in enumerate(retail.columns, 1):
    print(
        f"{i:2}. {col:<35} | "
        f"Kiểu: {str(retail[col].dtype):<10} | "
        f"Số giá trị khác nhau: {retail[col].nunique()}"
    )

 1. customer_id                         | Kiểu: int64      | Số giá trị khác nhau: 1000000
 2. age                                 | Kiểu: int64      | Số giá trị khác nhau: 62
 3. gender                              | Kiểu: str        | Số giá trị khác nhau: 3
 4. income_bracket                      | Kiểu: str        | Số giá trị khác nhau: 3
 5. loyalty_program                     | Kiểu: str        | Số giá trị khác nhau: 2
 6. membership_years                    | Kiểu: int64      | Số giá trị khác nhau: 10
 7. churned                             | Kiểu: str        | Số giá trị khác nhau: 2
 8. marital_status                      | Kiểu: str        | Số giá trị khác nhau: 3
 9. number_of_children                  | Kiểu: int64      | Số giá trị khác nhau: 5
10. education_level                     | Kiểu: str        | Số giá trị khác nhau: 4
11. occupation                          | Kiểu: str        | Số giá trị khác nhau: 4
12. transaction_id                      | Kiểu: int64      | Số giá trị khác nhau: 632576
13. transaction_date                    | Kiểu: str        | Số giá trị khác nhau: 992231
14. product_id                          | Kiểu: int64      | Số giá trị khác nhau: 9999
15. product_category                    | Kiểu: str        | Số giá trị khác nhau: 5
16. quantity                            | Kiểu: int64      | Số giá trị khác nhau: 9
17. unit_price                          | Kiểu: float64    | Số giá trị khác nhau: 99896
18. discount_applied                    | Kiểu: float64    | Số giá trị khác nhau: 51
19. payment_method                      | Kiểu: str        | Số giá trị khác nhau: 4
20. store_location                      | Kiểu: str        | Số giá trị khác nhau: 4
21. transaction_hour                    | Kiểu: int64      | Số giá trị khác nhau: 24
22. day_of_week                         | Kiểu: str        | Số giá trị khác nhau: 7
23. week_of_year                        | Kiểu: int64      | Số giá trị khác nhau: 52
24. month_of_year                       | Kiểu: int64      | Số giá trị khác nhau: 12
25. avg_purchase_value                  | Kiểu: float64    | Số giá trị khác nhau: 49001
26. purchase_frequency                  | Kiểu: str        | Số giá trị khác nhau: 4
27. last_purchase_date                  | Kiểu: str        | Số giá trị khác nhau: 984242
28. avg_discount_used                   | Kiểu: float64    | Số giá trị khác nhau: 51
29. preferred_store                     | Kiểu: str        | Số giá trị khác nhau: 4
30. online_purchases                    | Kiểu: int64      | Số giá trị khác nhau: 100
31. in_store_purchases                  | Kiểu: int64      | Số giá trị khác nhau: 100
32. avg_items_per_transaction           | Kiểu: float64    | Số giá trị khác nhau: 901
33. avg_transaction_value               | Kiểu: float64    | Số giá trị khác nhau: 49001
34. total_returned_items                | Kiểu: int64      | Số giá trị khác nhau: 10
35. total_returned_value                | Kiểu: float64    | Số giá trị khác nhau: 99999
36. total_sales                         | Kiểu: float64    | Số giá trị khác nhau: 629254
37. total_transactions                  | Kiểu: int64      | Số giá trị khác nhau: 99
38. total_items_purchased               | Kiểu: int64      | Số giá trị khác nhau: 499
39. total_discounts_received            | Kiểu: float64    | Số giá trị khác nhau: 99995
40. avg_spent_per_category              | Kiểu: float64    | Số giá trị khác nhau: 98999
41. max_single_purchase_value           | Kiểu: float64    | Số giá trị khác nhau: 99001
42. min_single_purchase_value           | Kiểu: float64    | Số giá trị khác nhau: 991
43. product_name                        | Kiểu: str        | Số giá trị khác nhau: 4
44. product_brand                       | Kiểu: str        | Số giá trị khác nhau: 3
45. product_rating                      | Kiểu: float64    | Số giá trị khác nhau: 41
46. product_review_count                | Kiểu: int64      | Số giá trị khác nhau: 1000
47. product_stock                       | Kiểu: int64      | Số giá trị khác nhau: 100
48. product_return_rate                 | Kiểu: float64    | Số giá trị khác nhau: 51
49. product_size                        | Kiểu: str        | Số giá trị khác nhau: 3
50. product_weight                      | Kiểu: float64    | Số giá trị khác nhau: 991
51. product_color                       | Kiểu: str        | Số giá trị khác nhau: 5
52. product_material                    | Kiểu: str        | Số giá trị khác nhau: 4
53. product_manufacture_date            | Kiểu: str        | Số giá trị khác nhau: 992037
54. product_expiry_date                 | Kiểu: str        | Số giá trị khác nhau: 992042
55. product_shelf_life                  | Kiểu: int64      | Số giá trị khác nhau: 365
56. promotion_id                        | Kiểu: int64      | Số giá trị khác nhau: 999
57. promotion_type                      | Kiểu: str        | Số giá trị khác nhau: 3
58. promotion_start_date                | Kiểu: str        | Số giá trị khác nhau: 984258
59. promotion_end_date                  | Kiểu: str        | Số giá trị khác nhau: 984252
60. promotion_effectiveness             | Kiểu: str        | Số giá trị khác nhau: 3
61. promotion_channel                   | Kiểu: str        | Số giá trị khác nhau: 3
62. promotion_target_audience           | Kiểu: str        | Số giá trị khác nhau: 2
63. customer_zip_code                   | Kiểu: int64      | Số giá trị khác nhau: 89999
64. customer_city                       | Kiểu: str        | Số giá trị khác nhau: 4
65. customer_state                      | Kiểu: str        | Số giá trị khác nhau: 3
66. store_zip_code                      | Kiểu: int64      | Số giá trị khác nhau: 89999
67. store_city                          | Kiểu: str        | Số giá trị khác nhau: 4
68. store_state                         | Kiểu: str        | Số giá trị khác nhau: 3
69. distance_to_store                   | Kiểu: float64    | Số giá trị khác nhau: 10001
70. holiday_season                      | Kiểu: str        | Số giá trị khác nhau: 2
71. season                              | Kiểu: str        | Số giá trị khác nhau: 4
72. weekend                             | Kiểu: str        | Số giá trị khác nhau: 2
73. customer_support_calls              | Kiểu: int64      | Số giá trị khác nhau: 20
74. email_subscriptions                 | Kiểu: str        | Số giá trị khác nhau: 2
75. app_usage                           | Kiểu: str        | Số giá trị khác nhau: 3
76. website_visits                      | Kiểu: int64      | Số giá trị khác nhau: 100
77. social_media_engagement             | Kiểu: str        | Số giá trị khác nhau: 3
78. days_since_last_purchase            | Kiểu: int64      | Số giá trị khác nhau: 365

In [10]:
# ============================================================
# TIỀN XỬ LÝ DATASET 1 - RETAIL
# ============================================================

# Tạo bản sao để không làm thay đổi dữ liệu gốc
retail_processed = retail.copy()

print("Kích thước trước tiền xử lý:", retail_processed.shape)


# 1. Chuyển transaction_date từ text sang datetime
retail_processed["transaction_date"] = pd.to_datetime(
    retail_processed["transaction_date"],
    errors="coerce"
)

print("\n=== KIỂM TRA TRANSACTION_DATE ===")
print("Kiểu dữ liệu:", retail_processed["transaction_date"].dtype)
print(
    "Số ngày không chuyển đổi được:",
    retail_processed["transaction_date"].isna().sum()
)


# 2. Tạo thuộc tính mới từ ngày giao dịch
retail_processed["transaction_year"] = (
    retail_processed["transaction_date"].dt.year
)

retail_processed["transaction_month"] = (
    retail_processed["transaction_date"].dt.month
)


# 3. Tạo giá trị giao dịch trước giảm giá
retail_processed["gross_value"] = (
    retail_processed["quantity"] *
    retail_processed["unit_price"]
)


# 4. Kiểm tra kết quả
print("\n=== THUỘC TÍNH MỚI ===")

display(
    retail_processed[
        [
            "transaction_date",
            "transaction_year",
            "transaction_month",
            "quantity",
            "unit_price",
            "gross_value"
        ]
    ].head()
)

print("\nKích thước sau khi thêm thuộc tính:", retail_processed.shape)

Kích thước trước tiền xử lý: (1000000, 78)

=== KIỂM TRA TRANSACTION_DATE ===
Kiểu dữ liệu: datetime64[us]
Số ngày không chuyển đổi được: 0

=== THUỘC TÍNH MỚI ===

,transaction_date,transaction_year,transaction_month,quantity,unit_price,gross_value
0,2020-10-11 10:08:52,2020,10,8,49.72,397.76
1,2021-12-08 01:07:40,2021,12,7,817.76,5724.32
2,2020-02-17 09:40:48,2020,2,8,270.30,2162.40
3,2020-08-13 00:43:14,2020,8,2,547.84,1095.68
4,2021-07-02 11:59:03,2021,7,4,785.29,3141.16

Kích thước sau khi thêm thuộc tính: (1000000, 81)

In [11]:
# ============================================================
# KIỂM TRA THUỘC TÍNH THỜI GIAN TRÙNG THÔNG TIN
# ============================================================

month_match = (
    retail_processed["transaction_month"]
    == retail_processed["month_of_year"]
).mean() * 100

print("Tỷ lệ transaction_month trùng month_of_year:",
      round(month_match, 2), "%")

print("\nCác năm có trong dữ liệu:")
print(
    retail_processed["transaction_year"]
    .value_counts()
    .sort_index()
)

print("\nKiểm tra gross_value:")
print(retail_processed["gross_value"].describe())

Tỷ lệ transaction_month trùng month_of_year: 8.34 %

Các năm có trong dữ liệu:
transaction_year
2020    500942
2021    499058
Name: count, dtype: int64

Kiểm tra gross_value:
count    1000000.000000
mean        2503.680609
std         2077.409421
min            1.000000
25%          797.015000
50%         1915.655000
75%         3773.250000
max         8999.820000
Name: gross_value, dtype: float64

In [12]:
# ============================================================
# KIỂM TRA TÍNH NHẤT QUÁN CỦA THUỘC TÍNH THỜI GIAN
# ============================================================

# Tạo tháng trực tiếp từ transaction_date
month_from_date = retail_processed["transaction_date"].dt.month

# So sánh với month_of_year có sẵn
inconsistent_month = (
    month_from_date != retail_processed["month_of_year"]
)

inconsistent_count = inconsistent_month.sum()
inconsistent_percent = (
    inconsistent_count / len(retail_processed) * 100
)

print("=== KIỂM TRA TÍNH NHẤT QUÁN ===")
print("Số bản ghi month_of_year không khớp transaction_date:",
      inconsistent_count)

print("Tỷ lệ không khớp:",
      round(inconsistent_percent, 2), "%")

print("\nVí dụ các bản ghi không khớp:")

display(
    retail_processed.loc[
        inconsistent_month,
        [
            "transaction_date",
            "month_of_year",
            "transaction_month"
        ]
    ].head(10)
)

=== KIỂM TRA TÍNH NHẤT QUÁN ===
Số bản ghi month_of_year không khớp transaction_date: 916602
Tỷ lệ không khớp: 91.66 %

Ví dụ các bản ghi không khớp:

      transaction_date  month_of_year  transaction_month
0  2020-10-11 10:08:52              7                 10
1  2021-12-08 01:07:40              2                 12
2  2020-02-17 09:40:48              6                  2
4  2021-07-02 11:59:03              3                  7
5  2020-12-01 16:31:54              2                 12
6  2020-03-14 22:58:48             10                  3
7  2021-11-17 15:56:04              9                 11
8  2020-05-18 08:48:18             10                  5
9  2020-03-10 18:03:08              8                  3
10 2021-10-13 08:07:17             11                 10

In [13]:
# ============================================================
# HOÀN THIỆN TIỀN XỬ LÝ DATASET 1 - RETAIL
# ============================================================

# 1. Sửa month_of_year dựa trên transaction_date
retail_processed["month_of_year"] = (
    retail_processed["transaction_date"].dt.month
)

# transaction_month được tạo trước đó giờ đã dư thừa
retail_processed.drop(
    columns=["transaction_month"],
    inplace=True
)

# 2. Kiểm tra lại tính nhất quán
month_check = (
    retail_processed["month_of_year"]
    == retail_processed["transaction_date"].dt.month
).mean() * 100

print("=== KIỂM TRA SAU TIỀN XỬ LÝ ===")
print(
    "Tỷ lệ month_of_year khớp transaction_date:",
    round(month_check, 2),
    "%"
)

print("Số giá trị thiếu:",
      retail_processed.isnull().sum().sum())

print("Số dòng trùng lặp:",
      retail_processed.duplicated().sum())

print("Kích thước dữ liệu cuối cùng:",
      retail_processed.shape)

=== KIỂM TRA SAU TIỀN XỬ LÝ ===
Tỷ lệ month_of_year khớp transaction_date: 100.0 %
Số giá trị thiếu: 0
Số dòng trùng lặp: 0
Kích thước dữ liệu cuối cùng: (1000000, 80)

In [14]:
# ============================================================
# LƯU DATASET 1 SAU TIỀN XỬ LÝ
# ============================================================

output_path = "../data/processed/retail_processed.csv"

retail_processed.to_csv(
    output_path,
    index=False
)

print("Đã lưu Dataset 1 thành công!")
print("Đường dẫn:", output_path)
print("Kích thước:", retail_processed.shape)

KeyboardInterrupt:

In [ ]:
# ============================================================
# TIỀN XỬ LÝ DATASET 2 - DIABETES
# BƯỚC 1: CHUẨN HÓA GIÁ TRỊ THIẾU
# ============================================================

# Tạo bản sao, không thay đổi dữ liệu raw
diabetes_processed = diabetes.copy()

# Chuyển ký hiệu "?" thành NaN
diabetes_processed = diabetes_processed.replace("?", np.nan)

print("=== GIÁ TRỊ THIẾU SAU KHI CHUẨN HÓA ===")

missing_count = diabetes_processed.isnull().sum()
missing_percent = (
    missing_count / len(diabetes_processed) * 100
).round(2)

missing_table = pd.DataFrame({
    "Số giá trị thiếu": missing_count,
    "Tỷ lệ thiếu (%)": missing_percent
})

missing_table = missing_table[
    missing_table["Số giá trị thiếu"] > 0
].sort_values(
    "Tỷ lệ thiếu (%)",
    ascending=False
)

display(missing_table)

print("\nTổng số thuộc tính có giá trị thiếu:",
      len(missing_table))

=== GIÁ TRỊ THIẾU SAU KHI CHUẨN HÓA ===

                   Số giá trị thiếu  Tỷ lệ thiếu (%)
weight                        98569            96.86
max_glu_serum                 96420            94.75
A1Cresult                     84748            83.28
medical_specialty             49949            49.08
payer_code                    40256            39.56
race                           2273             2.23
diag_3                         1423             1.40
diag_2                          358             0.35
diag_1                           21             0.02

Tổng số thuộc tính có giá trị thiếu: 9

In [ ]:
# ============================================================
# DATASET 2 - XỬ LÝ GIÁ TRỊ THIẾU
# ============================================================

# 1. Loại các thuộc tính có tỷ lệ thiếu trên 80%
high_missing_cols = [
    "weight",
    "max_glu_serum",
    "A1Cresult"
]

diabetes_processed.drop(
    columns=high_missing_cols,
    inplace=True
)

print("Đã loại các thuộc tính thiếu trên 80%:")
print(high_missing_cols)


# 2. Các thuộc tính phân loại còn thiếu:
# thay NaN bằng "Unknown"
remaining_missing_cols = [
    "medical_specialty",
    "payer_code",
    "race",
    "diag_1",
    "diag_2",
    "diag_3"
]

for col in remaining_missing_cols:
    diabetes_processed[col] = (
        diabetes_processed[col].fillna("Unknown")
    )


# 3. Kiểm tra lại
print("\n=== SAU KHI XỬ LÝ GIÁ TRỊ THIẾU ===")

print(
    "Tổng số giá trị thiếu còn lại:",
    diabetes_processed.isnull().sum().sum()
)

print(
    "Số thuộc tính còn lại:",
    diabetes_processed.shape[1]
)

print(
    "Kích thước dữ liệu:",
    diabetes_processed.shape
)

Đã loại các thuộc tính thiếu trên 80%:
['weight', 'max_glu_serum', 'A1Cresult']

=== SAU KHI XỬ LÝ GIÁ TRỊ THIẾU ===
Tổng số giá trị thiếu còn lại: 0
Số thuộc tính còn lại: 47
Kích thước dữ liệu: (101766, 47)

In [ ]:
# ============================================================
# DATASET 2 - KIỂM TRA TARGET VÀ THUỘC TÍNH ĐỊNH DANH
# ============================================================

print("=== PHÂN BỐ TARGET: readmitted ===")

target_count = diabetes_processed["readmitted"].value_counts()
target_percent = (
    diabetes_processed["readmitted"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

target_table = pd.DataFrame({
    "Số lượng": target_count,
    "Tỷ lệ (%)": target_percent
})

display(target_table)


print("\n=== KIỂM TRA THUỘC TÍNH ĐỊNH DANH ===")

id_cols = ["encounter_id", "patient_nbr"]

for col in id_cols:
    print(
        f"{col}: "
        f"{diabetes_processed[col].nunique()} giá trị khác nhau "
        f"/ {len(diabetes_processed)} bản ghi"
    )


print("\n=== SỐ GIÁ TRỊ KHÁC NHAU CỦA 47 THUỘC TÍNH ===")

for col in diabetes_processed.columns:
    print(f"{col:<30}: {diabetes_processed[col].nunique()}")

=== PHÂN BỐ TARGET: readmitted ===

            Số lượng  Tỷ lệ (%)
readmitted
NO             54864      53.91
>30            35545      34.93
<30            11357      11.16

=== KIỂM TRA THUỘC TÍNH ĐỊNH DANH ===
encounter_id: 101766 giá trị khác nhau / 101766 bản ghi
patient_nbr: 71518 giá trị khác nhau / 101766 bản ghi

=== SỐ GIÁ TRỊ KHÁC NHAU CỦA 47 THUỘC TÍNH ===
encounter_id                  : 101766
patient_nbr                   : 71518
race                          : 6
gender                        : 3
age                           : 10
admission_type_id             : 8
discharge_disposition_id      : 26
admission_source_id           : 17
time_in_hospital              : 14
payer_code                    : 18
medical_specialty             : 73
num_lab_procedures            : 118
num_procedures                : 7
num_medications               : 75
number_outpatient             : 39
number_emergency              : 33
number_inpatient              : 21
diag_1                        : 717
diag_2                        : 749
diag_3                        : 790
number_diagnoses              : 16
metformin                     : 4
repaglinide                   : 4
nateglinide                   : 4
chlorpropamide                : 4
glimepiride                   : 4
acetohexamide                 : 2
glipizide                     : 4
glyburide                     : 4
tolbutamide                   : 2
pioglitazone                  : 4
rosiglitazone                 : 4
acarbose                      : 4
miglitol                      : 4
troglitazone                  : 2
tolazamide                    : 3
examide                       : 1
citoglipton                   : 1
insulin                       : 4
glyburide-metformin           : 4
glipizide-metformin           : 2
glimepiride-pioglitazone      : 2
metformin-rosiglitazone       : 2
metformin-pioglitazone        : 2
change                        : 2
diabetesMed                   : 2
readmitted                    : 3

In [ ]:
# ============================================================
# HOÀN THIỆN TIỀN XỬ LÝ DATASET 2 - DIABETES
# ============================================================

# 1. Loại encounter_id vì chỉ là mã định danh duy nhất cho mỗi bản ghi
diabetes_processed.drop(
    columns=["encounter_id"],
    inplace=True
)

# 2. Kiểm tra lại toàn bộ dữ liệu
print("=== KIỂM TRA SAU TIỀN XỬ LÝ ===")

print("Kích thước dữ liệu:",
      diabetes_processed.shape)

print("Tổng số giá trị thiếu:",
      diabetes_processed.isnull().sum().sum())

print("Số dòng trùng lặp:",
      diabetes_processed.duplicated().sum())

print("Số thuộc tính dạng số:",
      len(diabetes_processed.select_dtypes(include=np.number).columns))

print("Số thuộc tính dạng phân loại/text:",
      len(diabetes_processed.select_dtypes(exclude=np.number).columns))

print("\nTarget readmitted:")
print(diabetes_processed["readmitted"].value_counts())

=== KIỂM TRA SAU TIỀN XỬ LÝ ===
Kích thước dữ liệu: (101766, 46)
Tổng số giá trị thiếu: 0
Số dòng trùng lặp: 0
Số thuộc tính dạng số: 12
Số thuộc tính dạng phân loại/text: 34

Target readmitted:
readmitted
NO     54864
>30    35545
<30    11357
Name: count, dtype: int64

In [ ]:
# ============================================================
# LƯU DATASET 2 SAU TIỀN XỬ LÝ
# ============================================================

output_path = "../data/processed/diabetes_processed.csv"

diabetes_processed.to_csv(
    output_path,
    index=False
)

print("Đã lưu Dataset 2 thành công!")
print("Đường dẫn:", output_path)
print("Kích thước:", diabetes_processed.shape)

Đã lưu Dataset 2 thành công!
Đường dẫn: ../data/processed/diabetes_processed.csv
Kích thước: (101766, 46)

In [ ]:
# ============================================================
# TIỀN XỬ LÝ DATASET 3 - HAR
# BƯỚC 1: GẮN TÊN CHO CÁC THUỘC TÍNH
# ============================================================

# Tạo bản sao
har_processed = har.copy()

# Lấy tên 561 thuộc tính từ features.txt
feature_names = features["feature_name"].tolist()

print("Số tên thuộc tính:", len(feature_names))
print("Số cột dữ liệu:", har_processed.shape[1])

# Kiểm tra tên thuộc tính bị trùng
duplicate_feature_names = (
    pd.Series(feature_names).duplicated().sum()
)

print("Số tên thuộc tính bị trùng:",
      duplicate_feature_names)

# Hiển thị 20 tên đầu tiên
print("\n=== 20 THUỘC TÍNH ĐẦU TIÊN ===")
for i, name in enumerate(feature_names[:20], 1):
    print(f"{i:2}. {name}")

Số tên thuộc tính: 561
Số cột dữ liệu: 561
Số tên thuộc tính bị trùng: 84

=== 20 THUỘC TÍNH ĐẦU TIÊN ===
 1. tBodyAcc-mean()-X
 2. tBodyAcc-mean()-Y
 3. tBodyAcc-mean()-Z
 4. tBodyAcc-std()-X
 5. tBodyAcc-std()-Y
 6. tBodyAcc-std()-Z
 7. tBodyAcc-mad()-X
 8. tBodyAcc-mad()-Y
 9. tBodyAcc-mad()-Z
10. tBodyAcc-max()-X
11. tBodyAcc-max()-Y
12. tBodyAcc-max()-Z
13. tBodyAcc-min()-X
14. tBodyAcc-min()-Y
15. tBodyAcc-min()-Z
16. tBodyAcc-sma()
17. tBodyAcc-energy()-X
18. tBodyAcc-energy()-Y
19. tBodyAcc-energy()-Z
20. tBodyAcc-iqr()-X

In [ ]:
# ============================================================
# DATASET 3 - HAR
# BƯỚC 2: CHUẨN HÓA TÊN THUỘC TÍNH VÀ THÊM NHÃN
# ============================================================

# 1. Làm tên thuộc tính thành duy nhất
unique_feature_names = []
name_count = {}

for name in feature_names:
    if name not in name_count:
        name_count[name] = 0
        unique_feature_names.append(name)
    else:
        name_count[name] += 1
        unique_feature_names.append(
            f"{name}_{name_count[name]}"
        )

# Gán tên mới cho 561 cột
har_processed.columns = unique_feature_names


# 2. Kiểm tra lại tên trùng
duplicate_after = (
    pd.Series(har_processed.columns)
    .duplicated()
    .sum()
)

print("=== KIỂM TRA TÊN THUỘC TÍNH ===")
print("Số cột:", har_processed.shape[1])
print("Số tên thuộc tính trùng sau xử lý:", duplicate_after)


# 3. Thêm mã hoạt động
har_processed["activity_id"] = har_target["activity"].values


# 4. Đọc bảng ánh xạ activity
activity_labels = pd.read_csv(
    f"{har_path}/activity_labels.txt",
    sep=r"\s+",
    header=None,
    names=["activity_id", "activity_name"]
)

activity_map = dict(
    zip(
        activity_labels["activity_id"],
        activity_labels["activity_name"]
    )
)

# Tạo tên hoạt động
har_processed["activity_name"] = (
    har_processed["activity_id"]
    .map(activity_map)
)


# 5. Kiểm tra kết quả
print("\n=== KẾT QUẢ DATASET 3 ===")
print("Kích thước:", har_processed.shape)

print("\nPhân bố hoạt động:")
print(
    har_processed["activity_name"]
    .value_counts()
)

print("\n5 cột cuối:")
print(har_processed.columns[-5:].tolist())

=== KIỂM TRA TÊN THUỘC TÍNH ===
Số cột: 561
Số tên thuộc tính trùng sau xử lý: 0

=== KẾT QUẢ DATASET 3 ===
Kích thước: (10299, 563)

Phân bố hoạt động:
activity_name
LAYING                1944
STANDING              1906
SITTING               1777
WALKING               1722
WALKING_UPSTAIRS      1544
WALKING_DOWNSTAIRS    1406
Name: count, dtype: int64

5 cột cuối:
['angle(X,gravityMean)', 'angle(Y,gravityMean)', 'angle(Z,gravityMean)', 'activity_id', 'activity_name']

In [ ]:
# ============================================================
# LƯU DATASET 3 SAU TIỀN XỬ LÝ
# ============================================================

output_path = "../data/processed/har_processed.csv"

har_processed.to_csv(
    output_path,
    index=False
)

print("Đã lưu Dataset 3 thành công!")
print("Đường dẫn:", output_path)
print("Kích thước:", har_processed.shape)

print("\n=== TỔNG KẾT DATASET 3 ===")
print("Số bản ghi:", har_processed.shape[0])
print("Số thuộc tính:", har_processed.shape[1])
print("Số giá trị thiếu:", har_processed.isnull().sum().sum())
print("Số dòng trùng lặp:", har_processed.duplicated().sum())

Đã lưu Dataset 3 thành công!
Đường dẫn: ../data/processed/har_processed.csv
Kích thước: (10299, 563)

=== TỔNG KẾT DATASET 3 ===
Số bản ghi: 10299
Số thuộc tính: 563
Số giá trị thiếu: 0
Số dòng trùng lặp: 0